### ISSUE TITLE
Improvements / Feature Requests

### ISSUE THREAD

**Issue by 919Studios** [marcamos/jet#1]
# Improvements / Feature Requests

## Concat/Minification to all added js & css files.
- [ ] Once you start mixing in fadable, custom web fonts, gsap etc, it would be cool if that was all minified/concatenated similar to how the css file is currently processed when we run the dev or build.

**Comment by marcamos** [comment]
By default, jet _does_ minify the stylesheet. To confirm, run `npm run build`, then look at `public/css/styles.css`.

JavaScript, however, is left entirely untouched.

In an effort to keep jet _very_ light and unopinionated, I'm going to leave it this way.
