### ISSUE TITLE
Build is slow

### ISSUE THREAD

**Issue by lud** [marcamos/jet#132]
Hello, 

First, thank your for that setup, it is very helpful and made me kickstart my website very quickly.

Now I do not understand why we need that code:

```javascript
  eleventyConfig.on('eleventy.after', async () => {
    console.log('Building Tailwind…');
    console.log(execSync('npm run build:tailwind').toString());
  });
```

It makes eleventy unresponsive when making changes.

I just removed it and everything seems fine, since the `dev` script calls the tailwind build anyway: `npm-run-all clean --parallel dev:*`. I just had to add `build:tailwind` in the `build` script, as in `NODE_ENV=production npm-run-all clean build:eleventy build:tailwind`.

And all is fine. Tthe build seems correct and changes to the markdown or templates are immediately refreshing the page in the browser.

Am I missing something here?

Thank you!

**Comment by marcamos** [comment]
@lud Thanks for writing this up; I'll take a look as soon as possible.

**Comment by ryanccn** [comment]
The post-build hook seems redundant and breaks Eleventy

**Comment by marcamos** [comment]
Looking into this a little (finally), I see that this chunk of code was introduced in https://github.com/marcamos/jet/pull/125 by @geshan. Before I investigate further, I thought I'd at least mention this. Based on what @geshan wrote in that pull request, this code improved things for them.

What does everyone think?

**Comment by geshan** [comment]
Just to add on it, this was working for me and it was needed when there were lots of posts to avoid race condition issues. If it is causing an issue I can revert PR #125 , let me know your thoughts.

**Comment by lud** [comment]
@geshan as I understand it, the files that tailwind looks to find what classes name to keep are the sources, not the build.

So in dev, the two builds (tailwind and posts) should be independent, which makes page refresh in browser very fast. With the current setup, any change to a page runs a build of tailwind _before_ updating the browser with the websocket and that makes it not very fluid to work with.

In build mode for prod, you do not care about the time, so you can run two commands instead of one, so the hook is not needed.

Finally, if you need to use the build result for tailwind filtering, the watch mode should already work.

**Comment by marcamos** [comment]
@geshan @lud Thank you both for your time and your attempts to improve jet.

I have a medium-to-large codebase running on jet already, with the code in question already in place, and things run fine. What I think I'll do (in the near future) is see how that same codebase runs if I comment-out the code in question.

**Comment by lud** [comment]
@marcamos can you try to update a markdown file and tell me if the refresh is instant in the browser?

To me it was not until I removed the hook.

But yeah, I can make my own changes since the project is not meant to be synced with git anyway :)

**Comment by marcamos** [comment]
@lud Absolutely! I'll do some testing as soon as I can, then report back.

**Comment by marcamos** [comment]
OK, here's my somewhat low-effort test results: I tested one jet-based codebase that's, I guess, _medium_ sized ([my personal blog](https://marcamos.com)), as well as the default jet codebase, both _before_ and _after_ making the suggested changes above.

---

**My blog, before removing the code as suggested above:**

* npm run dev: `[11ty] Copied 852 files / Wrote 61 files in 17.09 seconds (280.2ms each, v1.0.2)`
* After editing/saving a file: `[11ty] Copied 852 files / Wrote 61 files in 1.34 seconds (22.0ms each, v1.0.2)`
* npm run build: `[11ty] Copied 852 files / Wrote 61 files in 15.63 seconds (256.2ms each, v1.0.2)`

**My blog, after removing the code as suggested above:**

* npm run dev: `[11ty] Copied 852 files / Wrote 61 files in 14.94 seconds (244.9ms each, v1.0.2)`
* After editing/saving a file: `[11ty] Copied 852 files / Wrote 61 files in 0.53 seconds (8.7ms each, v1.0.2)`
* npm run build: `[11ty] Copied 852 files / Wrote 61 files in 14.88 seconds (243.9ms each, v1.0.2)`

---

**Default jet codebase, before removing the code as suggested above:**

* npm run dev: `[11ty] Copied 2 files / Wrote 1 file in 0.70 seconds (v1.0.2)`
* After editing/saving a file: `[11ty] Copied 2 files / Wrote 1 file in 0.70 seconds (v1.0.2)`
* npm run build: `[11ty] Copied 2 files / Wrote 1 file in 0.68 seconds (v1.0.2)`

**Default jet codebase, after removing the code as suggested above:**

* npm run dev: `[11ty] Copied 2 files / Wrote 1 file in 0.03 seconds (v1.0.2)`
* After editing/saving a file: `[11ty] Copied 2 files / Wrote 1 file in 0.02 seconds (v1.0.2)`
* Run npm run build: `[11ty] Copied 2 files / Wrote 1 file in 0.03 seconds (v1.0.2)`

---

So, yeah, it certainly looks like things run a bit faster if the suggested changes are made.

**Comment by lud** [comment]
Thank you for the tests! The main pain point to me is `After editing/saving a file`. The reload time in the browser is above two seconds for me with the code, from pressing Control+S to page reload. Obviously I just guessed the time, it is not something I can measure properly.

Anyway, as I said I am not asking to remove the code since I could just remove it from my own copy, but maybe a comment to tell that it is not strictly needed could be right.

**Comment by marcamos** [comment]
@lud You're welcome, and I definitely appreciate you bringing this up.

@geshan I'm leaning towards _removing_ this small chunk of code, and at the same time I'm curious: if you were to temporarily _remove_ it from your codebase, do you notice any issues (or, improvements)?
