### ISSUE TITLE
3 Vulnerabilities after installing jet

### ISSUE THREAD

**Issue by 919Studios** [marcamos/jet#2]
# 3 Vulnerabilities after installing jet
## after running: **npm i** there is a notice in terminal: _(SEE SCREENSHOT)_
![errors_When_Installing_Jet](https://user-images.githubusercontent.com/20955174/85613526-f8100280-b627-11ea-882a-9ccf4b2a256b.png)

----- 
## Running: "**npm audit fix**" does not resolve.

**Comment by marcamos** [comment]
These are vulnerabilities in the dependencies that jet relies on; they're out of my control, and will hopefully sort themselves out as the dependency authors update their packages over time.
