### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by olmesm** [marcamos/jet#26]
Thanks for putting this together - was literally about to roll my own as the starters are usually pretty crufty, but this is perfect.

**Comment by marcamos** [comment]
Wow, thanks for much for saying this; it made my morning!

Yeah, your sentiment is _exactly_ why I made jet — the other starters are super-handy, but I'm somewhat of a minimalist and would prefer to have much more control over _what_ features get added and _how_ they're added.

I used jet to build [my own blog](https://marcamos.com/) and it's extremely satisfying (to me) to know every piece of it.
