### ISSUE TITLE
Update to Tailwind 2.x

### ISSUE THREAD

**Issue by marcamos** [marcamos/jet#27]
Spend a little time with it, first, and if everything's smooth and simple, update to it.

**Comment by ryanccn** [comment]
https://github.com/ryanccn/ryanccn.dev/commit/e28c313cf2a6bf57d50acfcf11ee6039b59a407e

It's a pretty simple upgrade. Took me 15 minutes on [ryanccn.dev](https://ryanccn.dev) 😄

Just **follow the [upgrade guide](https://tailwindcss.com/docs/upgrading-to-v2)** and it should be okay.

**Comment by marcamos** [comment]
Fantastic, thanks for the tip @ryanccn!
