### ISSUE TITLE
bump tw to v 1.5.2 please and thank you :)

### ISSUE THREAD

**Issue by 919Studios** [marcamos/jet#4]
## Why this should be done:
- [x] Allows new tw components to work correctly.
- [x] Resolves previous npm vulnerabilities from tw previous version.  (**_just run npm audit to see its all fixed_**).

## How this can be done:
- [ ] Wont take more than a minute to do:  find the info **_[here](https://tailwindui.com/documentation#requirements)_** in the tailwind ui documentation.

**Comment by marcamos** [comment]
This has been bumped to `1.6.2` in https://github.com/marcamos/jet/commit/49c33cd42da60d2650eb2ec0753ef75097fe0f8e.
