### ISSUE TITLE
👋 Great project!

### ISSUE THREAD

**Issue by ryanccn** [marcamos/jet#5]
Hey there, I'm Ryan Cao

https://twitter.com/marcamos/status/1296459347774627843

I really like how it's just **11ty and Tailwind CSS** without Webpack or some other whatnot

And it's more optimized than my approach in the tweet

Thanks :wink:

**Comment by ryanccn** [comment]
One thing I don't get is, why is `postcss` and `tailwind` both involved in the build process?

**Comment by ryanccn** [comment]
In the `build` process:

```sh
$ npm run tailwind && postcss src/css/styles.css --replace
```

Isn't Tailwind run **twice**?

**Comment by marcamos** [comment]
Aha, I understand what you mean now — thanks for the clarification! You may be right; I'm going to do some testing as soon as I can, and I'll update this issue.

**Comment by marcamos** [comment]
I did some testing and here's what I discovered:

When I adjust the `build` script to be the following: `"postcss src/css/styles.css --replace && npm run clean && npx @11ty/eleventy"`, the compiled CSS _no longer_ picks up the classes in the HTML.

**Comment by marcamos** [comment]
Aha, but if I do _the opposite:_ remove the call to Tailwind from the postcss.config.js file, as seen in 339f02a2b43f8444ee874d8d48658385bb75f0df, it continues to work as desired.

Thank you so much @ryanccn! This has been a great tip.

**Comment by ryanccn** [comment]
Glad to help! :innocent:
