### ISSUE TITLE
Consider / apply Dependabot auto-merge Action

### ISSUE THREAD

**Issue by marcamos** [marcamos/jet#62]
via https://github.com/marketplace/actions/dependabot-auto-merge

**Comment by ryanccn** [comment]
@marcamos it needs a token in the **secrets** section so I can't do anything about it right now 😅

**Comment by marcamos** [comment]
Fantastic, thanks for your thoughts and the heads up about **secrets**!

**Comment by marcamos** [comment]
Trying this now — we should know if it's successful soon.

**Comment by marcamos** [comment]
It failed.

I poked around and found [this thread](https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/60), so, for now, I'll disable this feature and probably ease our notifications by changing Dependabot to run less frequently.
