### ISSUE TITLE
Not sure if i'm being stupid - Tailwind issue

### ISSUE THREAD

**Issue by PatrickWhitehouse** [marcamos/jet#97]
I'm not sure if I'm missing something obvious from the config, however, should altering .css files recompile tailwind without having to restart the npm task?

**Comment by marcamos** [comment]
Hey @PatrickWhitehouse! Nah, you're not being stupid or missing something obvious; what you're experiencing is what I experience too, and I don't like it either. I haven't had the time to look into it and see if there's a way to change it, unfortunately. That said, if you come across a way of changing it, please let me know and/or make a PR; I would be grateful.

**Comment by timkley** [comment]
@marcamos are you supporting Windows with this repo? If the answer is yes, how are your feelings about installing another 3rd-party-package, namely https://github.com/mysticatea/npm-run-all in this case?

**Comment by marcamos** [comment]
Hey @timkley! Yes, I am, thanks for asking. If you feel that it's advantageous and worthwhile, let's do it.

**Comment by marcamos** [comment]
@PatrickWhitehouse, this has been greatly improved by @timkley and is now available in https://github.com/marcamos/jet/releases/tag/3.0.0

**Comment by PatrickWhitehouse** [comment]
Thanks guys!
